# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
name: 'copyrights-action'
description: 'Check the presence of copyright notices in all text files'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'node20'
  main: 'src/copyrights.js'
inputs:
  license:
    description: 'The file with a license'
    required: true
    default: LICENSE.txt
  globs:
    description: 'Globs to check'
    required: true
    default: >-
      **/*.asm
      **/*.bib
      **/*.cls
      **/*.cpp
      **/*.dtx
      **/*.g4
      **/*.groovy
      **/*.h
      **/*.html
      **/*.ini
      **/*.ins
      **/*.java
      **/*.js
      **/*.lua
      **/*.pl
      **/*.properties
      **/*.py
      **/*.rb
      **/*.rs
      **/*.sh
      **/*.tex
      **/*.ts
      **/*.xml
      **/*.xsd
      **/*.xsl
      **/*.yaml
      **/*.yml
      Dockerfile
      Makefile
      Rakefile
  ignore:
    description: 'Globs to exclude'
    required: false
    default: >-
      .git/**
      target/**
      node_modules/**
